apiVersion: v1
kind: Service
metadata:
  name: tourism-website-service
  labels:
    app: tourism-website
spec:
  type: NodePort
  selector:
    app: tourism-website
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081